/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function CylinderLamp(props) {
  const { nodes, materials } = useGLTF("/cylinderLamp.glb");
  return (
    <group scale={[1, 1, 1]} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder000.geometry}
        material={nodes.Cylinder000.material}
        position={[-0.55, 0.72, 0.77]}
        scale={[0, 0.01, 0]}
      />
    </group>
  );
}

useGLTF.preload("/cylinderLamp.glb");
export default CylinderLamp;
