/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";


export function Headphones(props) {
  const { nodes, materials } = useGLTF("/headphones.glb");
  const ref = useRef(null)

  useFrame(({ clock }) => {
    ref.current.rotation.y = Math.sin(clock.getElapsedTime() / 100) * 50

})
  return (
    <group ref={ref} {...props} scale={[10, 10, 10]} dispose={null}>
      <group
        position={[0, 0.7802, 0.0158]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.002}
      >
        <group
          position={[-127.3795, 18.4891, -10.7643]}
          rotation={[0, -0.4577, -Math.PI / 2]}
        >
          <group
            position={[18.4891, -108.925, 68.0045]}
            rotation={[-0.6553, 0, 0]}
          >
            <group
              position={[0, 48.9375, 197.2962]}
              rotation={[-0.2229, 0, Math.PI / 2]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.foam_left_2.geometry}
                material={materials.Foam}
                position={[16.7617, 0, -3.8612]}
                rotation={[0, 0.0292, -Math.PI / 2]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.cup_left_2.geometry}
                material={materials.Cup}
              />
            </group>
            <group
              position={[-17.4337, 481.1739, 112.5259]}
              rotation={[2.295, 0, -1.5708]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.nuts_2_2.geometry}
                material={materials["Material.008"]}
                position={[0.0001, 0, 0]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.cup_handle_7.geometry}
              material={nodes.cup_handle_7.material}
              position={[-103.7901, 381.8762, 262.7961]}
              rotation={[0.1943, 0, 1.5369]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.cup_handle_2_1_2.geometry}
            material={materials.Foam}
            position={[-18.4891, 108.9249, -68.0045]}
            rotation={[-0.4611, 0, Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.cup_handle_3_1_2.geometry}
            material={materials.Hardware}
            position={[-18.4891, 108.9249, -68.0045]}
            rotation={[-0.4611, 0, Math.PI / 2]}
          />
        </group>
        <group
          position={[128.2313, 18.4891, -11.6321]}
          rotation={[0, -0.4577, -Math.PI / 2]}
        >
          <group
            position={[18.4891, 119.9968, -45.7166]}
            rotation={[-0.2618, 0, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.cup_handle_1_2.geometry}
              material={nodes.cup_handle_1_2.material}
              position={[-103.7901, -47.6567, 197.4782]}
              rotation={[-0.1993, 0, 1.5369]}
            />
            <group
              position={[0, -47.9501, 197.5374]}
              rotation={[0.2028, 0, Math.PI / 2]}
            >
              <group
                position={[58.3955, -2.532, -15.1893]}
                rotation={[0, -0.059, -Math.PI / 2]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.buttom_3.geometry}
                  material={materials.Hardware}
                  position={[0.3441, -0.1462, -0.3584]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.foam_right_2.geometry}
                material={materials.Foam}
                position={[61.1333, 0, -13.8427]}
                rotation={[0, -0.059, -Math.PI / 2]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.cup_handle_1b_2.geometry}
              material={materials.Hardware}
              position={[0, 0, 0.0001]}
            />
          </group>
          <group
            position={[-18.4891, -119.9968, 45.7166]}
            rotation={[-0.4611, 0, Math.PI / 2]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.cup_handle_5_2.geometry}
              material={materials.Top}
              position={[0, 0, -0.0001]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/headphones.glb");
