/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Plant(props) {
  const { nodes, materials } = useGLTF('/plant.glb')
  return (
    <group {...props} scale={[20, 20, 20]} position={[40, 0, -20]} rotation={[0, Math.PI/1.5, 0]} dispose={null}>
      <mesh geometry={nodes.Plant_10.geometry} material={materials.Plant_10_M} position={[0, 0, -1.23]} scale={2.01} castShadow/>
      <group position={[0, 0, -1.23]} scale={2.01}>
        <mesh geometry={nodes.Pot_10_Mesh.geometry} material={materials.Pot_Blue_glossy_M} castShadow/>
        <mesh geometry={nodes.Pot_10_Mesh_1.geometry} material={materials.Pot_soil_M} castShadow/>
      </group>
    </group>
  )
}

useGLTF.preload('/plant.glb')

export default Plant